### ISSUE TITLE
Column names in Flex Report SQL must be explicit

### ISSUE THREAD

**Issue by jamessun** [EASOL/easol#256]
Steps to reproduce: 

1. Visit http://easol-dev-staging.azurewebsites.net/reports/view/31 to view the results of a predefined query (or create a new Flex Report with the SQL listed below)

```
SELECT 'X', 1
UNION
SELECT 'Y', 2
```

I get both a PHP and a database error.

PHP error:
> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: Invalid argument supplied for foreach()
> 
> Filename: Reports/display-table.php
> 
> Line Number: 7
> 
> Backtrace:
> 
> File: D:\home\site\wwwroot\application\views\Reports\display-table.php
> Line: 7
> Function: _error_handler
> 
> File: D:\home\site\wwwroot\application\third_party\MX\Loader.php
> Line: 357
> Function: include
> 
> File: D:\home\site\wwwroot\application\third_party\MX\Loader.php
> Line: 300
> Function: _ci_load
> 
> File: D:\home\site\wwwroot\application\core\Easol_Controller.php
> Line: 69
> Function: view
> 
> File: D:\home\site\wwwroot\application\core\Easol_Controller.php
> Line: 36
> Function: renderPartial
> 
> File: D:\home\site\wwwroot\application\controllers\Reports.php
> Line: 198
> Function: render
> 
> File: D:\home\site\wwwroot\index.php
> Line: 292
> Function: require_once

SQL error:
> Error Number: 42000/8155
> 
> [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]No column name was specified for column 1 of 'b'.
> 
> SELECT count(*) as tot FROM (SELECT 'X', 1 UNION SELECT 'Y', 2) as b
> 
> Filename: D:/home/site/wwwroot/application/widgets/DataTableWidget/DataTableWidget.php
> 
> Line Number: 152

**Comment by edgarf** [comment]
@jamessun What should be the expected outcome of
```SELECT 'X', 1
UNION
SELECT 'Y', 2```
query? I assume an empty list, is that correct?

**Comment by jamessun** [comment]
In SQL Server, 
```
SELECT 'X' AS XAxis, 1 AS YAxis
UNION
SELECT 'Y', 2
```
returns
```
XAxis YAxis
----- -----------
X     1
Y     2

(2 row(s) affected)
```
Maybe you're thinking about the difference between UNION and UNION ALL? UNION ALL includes duplicates while UNION removes duplicates.

**Comment by edgarf** [comment]
Hey James,

I have deployed those small updates into easol-dev environment, could you please check  http://easol-dev.azurewebsites.net/reports/view/50 <http://easol-dev.azurewebsites.net/reports/view/50> this? Also, I think other issues are solved which were before with PIVOT, ORDER BY etc. Could you please take a look at those? The only issue I found is that UNION doesn’t work with ORDER BY, which we are investigating right now.

Regards,
Edgar

**Comment by jamessun** [comment]
Edgar -

That's great! I'll try out different kinds of SQL to see what works.

Does the Filter functionality work in easol-dev?

James

**Comment by jamessun** [comment]
Edgar - 

The original issue still exists, but the UI handles it a bit more gracefully. If a Flex Report is defined with one (or more) columns that don't have a column name/alias, nothing is returned.

See http://easol-dev.azurewebsites.net/reports/edit/54

James

**Comment by edgarf** [comment]
Thanks, yes you should add "WHERE/AND $filter"  or it can be $filters, not by PC Right now, cant check. Sorry.
Edgar

**Comment by edgarf** [comment]
@jamessun 
```
SELECT 
'X' AS XAxis
, 1 AS YAxis
, 2
```
So this should be working the other way, correct? OK, I will test with SQL Tool. Thanks.
